name: ESLint

on:
  push:
    branches: [ "main" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "main" ]
  schedule:
    - cron: '16 3 * * 2'

jobs:
  eslint:
    name: Run eslint scanning
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Setup Node 16
        uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: Setup pnpm
        uses: pnpm/action-setup@v2.2.4
        with: 
          version: 7.14.0
      - name: Install Dependencies
        run: pnpm i
      - name: Run ESLint
        run: npx eslint -c .eslintrc.json --ext .js,.ts,.vue ./packages
          
        
